[workspace]
members = [
  "generate_ast",
]

[package]
name = "rs-crafting-interpreters"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.90"  }
thiserror = { version = "1.0.64"  }
